language: csharp
solution: TuplesTLAS/TuplesTLAS.sln
env:
  global:
    - EnableNuGetPackageRestore=true
  install:
    - nuget restore TuplesTLAS/TuplesTLAS.sln
  script: 
    - xbuild
    - ./build.sh
  os:
    - windows
    - osx
  mono:
    - 3.12.0
    - 3.10.0