language: csharp
solution: TuplesTLAS/TuplesTLAS.sln
os:
  - linux
install:
  - nuget restore TuplesTLAS/TuplesTLAS.sln
  - nuget install NUnit.Console -Version 3.10.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release TuplesTLAS/TuplesTLAS.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe ./TuplesTLAS/TuplesTLASTests/bin/Release/TuplesTLASTests.dll


#env:  
#  before_install:
#  - sudo apt-get install nunit-console
#  before_script:
#  - nuget restore TuplesTLAS/TuplesTLAS.sln
#  after-script:
#    - nunit-console TuplesTLAS/TuplesTLASTests/bin/Release/TuplesTLASTests.dll
