language: csharp
solution: TuplesTLAS/TuplesTLAS.sln
env:
  global:
    - EnableNuGetPackageRestore=true
  before_install:
    - sudo apt-get install nunit-console
  install:
    - nuget restore TuplesTLAS/TuplesTLAS.sln
  script: 
    - nunit
  after-script:
    - nunit-console TuplesTLAS/TuplesTLASTests/bin/Debug/TuplesTLASTests.dll
  os:
    - windows
    - osx
  mono:
    - 3.12.0
    - 3.10.0