language: csharp
solution: TuplesTLAS/TuplesTLAS.sln
env:
  before_install:
  - sudo apt-get install nunit-console
  before_script:
  - nuget restore TuplesTLAS/TuplesTLAS.sln
  after-script:
    - nunit-console TuplesTLAS/TuplesTLASTests/bin/Release/TuplesTLASTests.dll
  os:
    - windows
    - osx
  mono:
    - 3.12.0
    - 3.10.0